# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779b0d5d79a98bdbb79f1c1bf3c679e7f76dbf3e8734cfdd3a34b20016f319209f6c8d86a22d8370d3390004a255de1bf2fc7d5754be385cb211945916415fd2

test:
  secret_key_base: d9040b4951d9cc5515938e40fcb341cd65e48a7875c48a146854fe291362ca73790aa907c70ff85ff212757b6c094f7d2e30ac83ccc464d0827834329996f88d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
